### ISSUE TITLE
Check if .swift files are directories

### ISSUE THREAD

**Issue by stephencelis** [realm/SwiftCov#42]
A convention I've used and seen used elsewhere it to name the repo **$(TARGET_NAME).swift**, which is thus cloned as the directory, too (_e.g._ Dollar.swift, Few.swift, SQLite.swift).

I discovered from reading the source that `-- $SOURCE_DIR` works, but figure it would be a good bug to fix. I'd dig in deeper now but couldn't get the tests to run and need to run to work :stuck_out_tongue:

**Comment by jpsim** [comment]
Definitely a good idea!

**Comment by jpsim** [comment]
Could probably be done quite easily in `coverage.py`: https://github.com/realm/SwiftCov/blob/0.1.0/Source/SwiftCovFramework/coverage.py#L172-L176
