### ISSUE TITLE
Make Install doesn't work.

### ISSUE THREAD

**Issue by shahzadmajeed** [realm/SwiftCov#65]
Here is what it says

user-a100040:SwiftCov user$ sudo make install
rm -f "SwiftCov.pkg"
rm -rf "/tmp/SwiftCov.dst"
xcodebuild -workspace 'SwiftCov.xcworkspace' -scheme 'swiftcov' -configuration 'Release' -sdk macosx DSTROOT=/tmp/SwiftCov.dst clean
Build settings from command line:
    DSTROOT = /tmp/SwiftCov.dst
    SDKROOT = macosx10.12

=== CLEAN TARGET SwiftCovFramework OF PROJECT swiftcov WITH CONFIGURATION Release ===

Check dependencies
The file “Release.xcconfig” couldn’t be opened because there is no such file. (/Users/user/Downloads/SwiftCov/Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig)
The file “Mac-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/user/Downloads/SwiftCov/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig)
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
make: *** [clean] Error 65

**Comment by jpsim** [comment]
This project has been entirely obsoleted by the native code coverage generation support available in Swift 2 onwards. It is therefore no longer maintained or supported.
